language: node_js
node_js:
  - '8'
  - '10'
install:
  - yarn install --ignore-engines
  - yarn global add codecov
before_script:
  - yarn lerna run lint
script:
  - yarn lerna run test --stream
  - codecov
deploy:
  provider: script
  script: 'git checkout master && yarn lerna publish'
  skip_cleanup: true
  on:
    node: '10'
    branch: master
